
FRASES = [
    "A vida trará coisas boas se tiveres paciência.",
    "Demonstre amor e alegria em todas as oportunidades e verás que a paz nasce dentro de você.",
    "Não compense na ira o que lhe falta na razão.",
    "Defeitos e virtudes são apenas dois lados da mesma moeda.",
    "A maior de todas as torres começa no solo.",
    "Não há que ser forte, mas sim flexível.",
    "Gente todo dia arruma os cabelos, por que não o coração?",
    "Há três coisas que jamais voltam: a flecha lançada, a palavra dita e a oportunidade perdida.",
    "A juventude não é uma época da vida, é um estado de espírito.",
    "Vencer a si próprio é a maior das vitórias.",
    "Deixe de lado as preocupações e seja feliz.",
    "Realize o óbvio, pense no improvável e conquiste o impossível.",
    "Acredite em milagres, mas não dependa deles.",
    "A sorte favorece a mente bem preparada.",
    "Seu esforço será recompensado.",
    "aplicar o conhecimento e o entendimento",
    "O conhecimento é saber que nada se sabe",
    "Para ganhar conhecimento, adicione coisas todos os dias",
    "O homem superior atribui a culpa a si próprio; o homem comum, aos outros",
    "O ignorante afirma, o sábio duvida, o sensato reflete",
    "Plante um pensamento, colha uma ação",
    "Conhecer os outros é inteligência, conhecer-se a si próprio é verdadeira sabedoria",
    "A maior sabedoria é ter o presente como objeto maior da vida, pois ele é a única realidade",
    "Não confunda jamais conhecimento com sabedoria. Um o ajuda a ganhar a vida; o outro, a construir uma vida",
    "O silêncio é a oração dos sábios"
]
